{% set name = "metanetx-post" %}
{% set version = "0.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 798d375a4e643a17e080f63bfc5705ccdb9066cfd0459390568ed5851d521b4d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed"
  entry_points:
    - "mnx-post = metanetx_post.cli.main:cli"

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - aioftp
    - click
    - click-log
    - cobra-component-models
    - depinfo
    - httpx
    - metanetx-assets
    - metanetx-sdk
    - pandas
    - pydantic
    - pyparsing
    - python >=3.8
    - rdflib
    - rdkit
    - sqlalchemy
    - tqdm

test:
  imports:
    - metanetx_post
  commands:
    - "mnx-post --help"

about:
  home: https://pypi.org/project/metanetx-post/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Enrich the information coming from MetaNetX (https://metanetx.org) with additional sources."
  description: |
    This package provides a command line program 'mnx-post' that has a number of
    commands to augment the existing information from MetaNetX from other
    sources, among them BiGG, ExPASy, KEGG, and SEED.
  dev_url: https://github.com/Midnighter/metanetx-post

extra:
  recipe-maintainers:
    - Midnighter
